feat: creating cloudflare adapter
ecomclub/storage-api pull request #7
Opened 2022-01-28 13:41 UTC by Mazurco066

Adding cloudinary

2022-01-28 23:50 UTC, leomp12 commented
👀

2022-01-29 04:27 UTC, leomp12 commented on bin/web.js
> +            }
```suggestion
            // S3 Response
            .then(() => {
              logger.log(`${storeId} ${key} Uploaded to ${bucket}`)
              // zoom uploaded
              const mountUri = (key, baseUrl = cdnHost || host) => `https://${baseUrl}/${storeId}/${key}`
              const uri = mountUri(key)
              const picture = { zoom: { url: uri } }
              const pictureBytes = {}
              // resize/optimize image
              let i = -1
              let transformedImageBody = null

              const respond = () => {
                logger.log(`${storeId} ${key} ${bucket} All optimizations done`)
                res.json({ bucket, key, uri, picture })
              }
```

2022-01-29 05:12 UTC, leomp12 requested changes
@Mazurco066 foi bem man!
mas tem umas coisas que comentei que dariam BO 😝 

> se rolar quebrar menos indentação (manter a anterior) facilita o review também 🕊️

2022-01-29 05:12 UTC, leomp12 commented on lib/Cloudflare.js
> +        download(`${normalImage}`, (err, imageBody) => {
aqui voce vai baixar sempre a imagem `normal`, mas ao mesmo tempo você tá percorrendo todos os sizes no upload e jogando pro s3, certo?
aí todas as variações salvas no s3 na verdade vão ser referentes as dimensões `normal` :grimacing:
acho que na sua implementação o `size` tem que ser um argumento da função de transformacao aqui...

2022-01-29 05:12 UTC, leomp12 commented on lib/Cloudflare.js
> +  const cloudinaryClient = axios.create({
```suggestion
  const cloudflareClient = axios.create({
```

2022-01-29 05:12 UTC, leomp12 commented on lib/Cloudflare.js
> +    cloudinaryClient({
```suggestion
    cloudflareClient({
```

2022-01-29 05:12 UTC, leomp12 commented on lib/Cloudflare.js
> +          setTimeout(() => cloudinaryClient.delete(`/images/v1/${id}`), 60000)
```suggestion
          setTimeout(() => cloudflareClient.delete(`/images/v1/${id}`), 60000)
```

2022-01-29 05:12 UTC, leomp12 commented on lib/Cloudflare.js
> +            ...response.data.result
```suggestion
            ...response.data.result,
            url: normalImage,
            imageBody
```

vai que tem um `url` ou `imageBody` nesse `response.data.result`...

2022-01-29 05:12 UTC, leomp12 commented on lib/Cloudflare.js
> +      const normalImage = variants.find(v => v.includes('normal')) || variants[0]
além de variar o `size` aqui, nao era melhor ser mais específico um pouco no match do url? tipo:
```js
const url = variants.find(v => v.endsWith(`/${size}`)) || variants[0]
```

2022-01-29 05:12 UTC, leomp12 commented on bin/web.js
> +                              contentType = `image/${filename.includes('.png') ? 'png' : filename.includes('.webp') ? 'webp' : 'jpeg'}`
aparentemente a intencao aqui era indentificar se imagem foi parseada (content type diferente da imagem original), certo? nesse caso, chegou a validar se o esse filename na resposta do cf images tem a extensão da imagem parseada?

quer dizer, se o cf images retorna nesse filename o nome do arquivo original, isso aqui não vai resolver nosso problema, porque nesse caso se você fizer o upload de abacate.png e ele parsear para webp, mesmo assim ele retornaria abacate.png e o nosso content type ficaria png (incorreto)...

se você já entendeu e testou isso, ótimo!

2022-01-29 05:12 UTC, leomp12 commented on bin/web.js
> +                              contentType = `image/${filename.includes('.png') ? 'png' : filename.includes('.webp') ? 'webp' : 'jpeg'}`
mais um detalhe, existem outras extensões de imagens, tipo gif e avif, que nessa sua implementação não seriam cobertas...

2022-01-29 05:12 UTC, leomp12 commented on bin/web.js
> +                              contentType = `image/${filename.includes('.png') ? 'png' : filename.includes('.webp') ? 'webp' : 'jpeg'}`
e outra, pelo que vi o url da imagem no s3 vai ficar sem a extensão porque você parou de concatenar o `newKey`

2022-01-29 05:12 UTC, leomp12 commented on bin/web.js
> +                              contentType = `image/${filename.includes('.png') ? 'png' : filename.includes('.webp') ? 'webp' : 'jpeg'}`
nao é melhor manter mais ou menos como estava, só trocando o `format` por `filename`? 😛

2022-01-31 17:36 UTC, Mazurco066 commented on lib/Cloudflare.js
> +  const cloudinaryClient = axios.create({
Resolvido

2022-01-31 17:37 UTC, Mazurco066 commented on lib/Cloudflare.js
> +    cloudinaryClient({
Resolvido

2022-01-31 17:37 UTC, Mazurco066 commented on lib/Cloudflare.js
> +          setTimeout(() => cloudinaryClient.delete(`/images/v1/${id}`), 60000)
Resolvido

2022-01-31 17:37 UTC, Mazurco066 commented on lib/Cloudflare.js
> +            ...response.data.result
Resolvido

2022-01-31 17:37 UTC, Mazurco066 commented on lib/Cloudflare.js
> +      const normalImage = variants.find(v => v.includes('normal')) || variants[0]
Resolvido

2022-01-31 19:05 UTC, Mazurco066 commented on lib/Cloudflare.js
> +        download(`${normalImage}`, (err, imageBody) => {
Resolvido

2022-02-01 00:45 UTC, leomp12 commented on bin/web.js
> +            }
não tá errado, mas acho que tbm não gastava isso aqui não man..

só um ternário já resolvia:

```js
label === 'small' ? 'w90' : label
```

2022-02-01 00:45 UTC, leomp12 commented on lib/Cloudflare.js
> +        download(`${url}`, (err, imageBody) => {
ainda vai editar o download aqui por causa do user agent como conversamos né?

2022-02-01 14:19 UTC, Mazurco066 commented on bin/web.js
> +                              contentType = `image/${filename.includes('.png') ? 'png' : filename.includes('.webp') ? 'webp' : 'jpeg'}`
Resolvido criando um novo Downloader utilizando axios e os headers para mudar retorno da cloudflare para webp: { 'Accept': 'image/webp,image/webp,image/*,*/*;q=0.8' }

2022-02-01 14:20 UTC, Mazurco066 commented on lib/Cloudflare.js
> +        download(`${url}`, (err, imageBody) => {
Donwnload foi modificado, está agora em um novo arquivo para a cloudflare

2022-02-01 14:21 UTC, Mazurco066 commented on bin/web.js
> +            }
Resolvido

2022-02-01 18:10 UTC, leomp12 commented on lib/Cloudflare.js
> +        download(url, { 'Accept': 'image/webp,image/webp,image/*,*/*;q=0.8' }, (err, imageBody) => {
não deve ser um problema até, mas acho que esse `image/webp` não precisava ser duplicado aqui...

2022-02-01 18:10 UTC, leomp12 commented on bin/web.js
> +                        cloudflare(imageBase64 || originUrl, label === 'small' ? 'w90' : label, (err, data) => {
tl;dr:

```js
const pictureOptims = (pictureSizes || [700, 350]).map((size, i) => {
  const label = i === 0 ? 'big' : i === 1 ? 'normal' : 'small'
  return { size, label, webp: true }
})
```

na verdade teve uma alteração de funcionamento aqui também, antes passávamos o arg `webp` (nome ruim) na função de transformação porque as imagens seriam transformadas duas vezes, uma pra webp e outra sem webp, até acho que agora tá tudo bem não fazermos isso porque quase todo browser decente suporta webp, mas nesse caso devemos alterar também o trecho: https://github.com/ecomplus/storage-api/blob/da504b62a85e14070a6e735e8f57b014ee4ce535/bin/web.js#L48-L51 

quer dizer, pra cada size tá sendo adicionado duas transformações a fezer, uma com resize e parse pra webp, outra com resize e sem webp, como agora (na função `cloudflare`) o `webp` não é um argumento, pra cada size estaremos chamando a função duas vezes com os mesmos argumentos e portanto mesmo output (só duplicado atoa 😄 )

2022-02-01 18:41 UTC, Mazurco066 commented on bin/web.js
> +                        cloudflare(imageBase64 || originUrl, label === 'small' ? 'w90' : label, (err, data) => {
OK

2022-02-01 18:42 UTC, Mazurco066 commented on lib/Cloudflare.js
> +        download(url, { 'Accept': 'image/webp,image/webp,image/*,*/*;q=0.8' }, (err, imageBody) => {
Testei sem e não é um problema então OK

2022-02-01 19:02 UTC, leomp12 approved these changes
boa @Mazurco066 ! 🥇

2022-02-01 19:12 UTC, merged